/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.gltf 
Author: Villius (https://sketchfab.com/villius12346)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dron-0e8736c08a31438c8d090ccdcc7d0973
Title: Dron
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('../robotModel/robot.gltf')
  return (
    <group {...props} dispose={null} scale={1}>
      <group position={[-0.203, -0.19, -3.096]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Blue_light} />
      </group>
      <group rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[0.656, -0.657, -0.286]} rotation={[Math.PI / 2, -Math.PI / 4, -1.163]}>
        <mesh geometry={nodes.Object_36.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[-0.657, -0.656, -0.286]} rotation={[-Math.PI / 2, -Math.PI / 4, 1.978]}>
        <mesh geometry={nodes.Object_39.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Dark_metal} />
      </group>
      <group position={[-0.596, 0.582, -0.81]} rotation={[1.018, 0.708, -1.189]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Blue_light} />
      </group>
      <group position={[0.596, -0.582, -0.81]} rotation={[-1.018, -0.708, 1.953]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.Blue_light} />
      </group>
      <group position={[-0.596, 0.582, -0.81]} rotation={[1.018, 0.708, -1.189]}>
        <mesh geometry={nodes.Object_64.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Blue_light} />
      </group>
      <group position={[0.582, 0.596, -0.81]} rotation={[1.02, -0.703, -1.949]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.Blue_light} />
      </group>
      <group position={[-0.582, -0.596, -0.81]} rotation={[-1.02, 0.703, 1.193]}>
        <mesh geometry={nodes.Object_76.geometry} material={materials.Light_metal} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Corpus} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.Fire} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.Blue_light} />
      </group>
      <group position={[1.244, -0.19, -2.832]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Object_156.geometry} material={materials.Dark_metal} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.Blue_light} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Corpus} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Corpus} rotation={[-1.571, 0.803, 0.799]} scale={0.27} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Dark_metal} rotation={[-Math.PI / 2, 1.396, Math.PI]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Corpus} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Blue_light} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Light_metal} position={[0, -0.521, 0.845]} rotation={[2.043, Math.PI / 2, 0]} scale={[0.024, 0.024, 0.016]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Blue_light} rotation={[-Math.PI / 2, 1.396, Math.PI]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Dark_metal} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Corpus} rotation={[1.571, 0.768, -2.343]} scale={0.27} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Corpus} rotation={[1.571, -0.803, -2.343]} scale={0.27} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Corpus} rotation={[-1.571, -0.768, 0.798]} scale={0.27} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Corpus} position={[-2.761, 2.7, -2.031]} rotation={[1.029, 0.687, -1.204]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Light_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Dark_metal} scale={0.218} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Dark_metal} scale={0.218} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Dark_metal} position={[3.738, 0, 0]} scale={0.218} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Dark_metal} scale={0.218} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Fire} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Dark_metal} position={[0, 0, -0.864]} rotation={[0, 0, 2.356]} scale={0.086} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Dark_metal} position={[-0.447, -0.624, 2.294]} rotation={[-1.382, 0.02, 0.104]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Dark_metal} position={[-0.451, -0.664, 2.256]} rotation={[-0.829, 0.072, 0.078]} scale={0.007} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Dark_metal} position={[-0.458, -0.689, 2.191]} rotation={[-0.35, 0.099, 0.036]} scale={0.007} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Dark_metal} position={[-0.457, -0.37, 2.2]} rotation={[0.669, 0.083, 3.076]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Dark_metal} position={[-0.463, -0.365, 2.145]} rotation={[0.112, 0.105, 3.13]} scale={0.007} />
      <mesh geometry={nodes.Object_108.geometry} material={materials.Dark_metal} position={[-0.47, -0.389, 2.08]} rotation={[-0.369, 0.099, -3.104]} scale={0.007} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Dark_metal} position={[-0.586, -0.497, 2.261]} rotation={[-0.432, 1.121, -1.486]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Dark_metal} position={[-0.616, -0.514, 2.218]} rotation={[-0.379, 0.567, -1.527]} scale={0.007} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Dark_metal} position={[-0.623, -0.539, 2.152]} rotation={[-0.359, 0.089, -1.534]} scale={0.007} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Dark_metal} position={[-0.318, -0.497, 2.232]} rotation={[-0.307, -0.924, 1.632]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials.Dark_metal} position={[-0.298, -0.514, 2.184]} rotation={[-0.341, -0.369, 1.61]} scale={0.007} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Dark_metal} position={[-0.305, -0.539, 2.118]} rotation={[-0.359, 0.108, 1.608]} scale={0.007} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Dark_metal} position={[-0.481, -0.598, 1.968]} rotation={[-Math.PI, 1.465, -1.928]} scale={0.086} />
      <mesh geometry={nodes.Object_124.geometry} material={materials.Dark_metal} position={[0.988, -0.765, 2.229]} rotation={[-1.285, -0.484, 0.226]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials.Dark_metal} position={[1.004, -0.8, 2.189]} rotation={[-0.718, -0.295, 0.447]} scale={0.007} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Dark_metal} position={[1.009, -0.82, 2.122]} rotation={[-0.29, -0.067, 0.526]} scale={0.007} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Dark_metal} position={[0.853, -0.545, 2.151]} rotation={[0.633, 0.401, -2.784]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_132.geometry} material={materials.Dark_metal} position={[0.844, -0.539, 2.097]} rotation={[0.109, 0.162, -2.635]} scale={0.007} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Dark_metal} position={[0.849, -0.559, 2.03]} rotation={[-0.306, -0.077, -2.617]} scale={0.007} />
      <mesh geometry={nodes.Object_136.geometry} material={materials.Dark_metal} position={[0.804, -0.722, 2.202]} rotation={[-0.941, 0.774, -0.795]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_138.geometry} material={materials.Dark_metal} position={[0.786, -0.749, 2.157]} rotation={[-0.54, 0.331, -1.013]} scale={0.007} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.Dark_metal} position={[0.791, -0.769, 2.09]} rotation={[-0.293, -0.08, -1.045]} scale={0.007} />
      <mesh geometry={nodes.Object_142.geometry} material={materials.Dark_metal} position={[1.037, -0.588, 2.178]} rotation={[0.446, -0.886, 2.483]} scale={[0.008, 0.013, 0.013]} />
      <mesh geometry={nodes.Object_144.geometry} material={materials.Dark_metal} position={[1.062, -0.59, 2.129]} rotation={[-0.041, -0.471, 2.167]} scale={0.007} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Dark_metal} position={[1.067, -0.61, 2.062]} rotation={[-0.303, -0.064, 2.096]} scale={0.007} />
      <mesh geometry={nodes.Object_148.geometry} material={materials.Dark_metal} position={[0.94, -0.741, 1.904]} rotation={[-1.745, 1.041, 2.998]} scale={0.086} />
      <mesh geometry={nodes.Object_150.geometry} material={materials.Dark_metal} position={[-0.485, -0.613, 1.938]} rotation={[-Math.PI, 1.465, -1.928]} scale={0.104} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Dark_metal} position={[-0.485, -0.613, 1.938]} rotation={[-Math.PI, 1.465, -1.928]} scale={0.104} />
      <mesh geometry={nodes.Object_154.geometry} material={materials.Dark_metal} position={[0.945, -0.752, 1.874]} rotation={[-1.745, 1.041, 2.998]} scale={0.104} />
      <mesh geometry={nodes.Object_159.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.Dark_metal} rotation={[Math.PI / 2, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('../robotModel/robot.gltf')
